### ISSUE TITLE
About edge boxes generation

### ISSUE THREAD

**Issue by ppeterpp** [Zx55/SiameseDETR#1]
In command for EdgeBoxes generation below:
`sh run.sh <YOUR_PARTITION> <NUM_PROCESS> <PATH/TO/DATA/ROOT> <PATH/TO/DATA/META> <PATH/TO/SAVE/DIR> <DATASET>  # <DATASET> should be imagenet or coco`
What kind of file does <PATH/TO/DATA/META> refer to, and how can I acquire such files?

**Comment by Zx55** [comment]
<PATH/TO/DATA/META> refers to a meta file, e.g., data/datasets/imagenet/meta/train.txt

**Comment by ppeterpp** [comment]
Thanks for your help! 
Is it that coco as well as voc also contain such meta files, and if so please specify them!

**Comment by Zx55** [comment]
You can generate meta files for coco/voc easily.

The key implementation of the Edgeboxes generator is like
```
path = os.path.join(self.root, line.split()[0])
box = self.box_generator.process(path)
```

So just make sure the meta file is like 

```
data1.jpg
data2.jpg
data3.jpg
...
```

**Comment by ppeterpp** [comment]
Thanks, that makes sense, and one more question: is it possible to generate edgeboxes without 'srun'? It is quite complicated to make your given run.sh for edgeboxes work…
