### ISSUE TITLE
About voc meta files

### ISSUE THREAD

**Issue by ppeterpp** [Zx55/SiameseDETR#2]
"We provide coco-style PASCAL VOC meta files (See `data/datasets/voc_meta`) for downstream finetuning."
As is stated in the readme, the `data/datasets/voc_meta` directory and files are supposed to be included in the repo. Would you please provide it?

**Comment by Zx55** [comment]
coco-style voc meta file has been uploaded. See `https://github.com/Zx55/SiameseDETR/tree/main/data/datasets/voc_meta`.
