### ISSUE TITLE
How to generate personal coco-style PASCAL VOC meta

### ISSUE THREAD

**Issue by everytimeis80** [Zx55/SiameseDETR#3]
I would like to apply your work to my own dataset and ask how to generate the corresponding coco-style PASCAL VOC meta. Thank you for your reply

**Comment by Zx55** [comment]
Hi, coco-style meta file refers to aligning the format of PASCAL VOC's meta file with the JSON format of coco's meta file. This alignment allows us to use coco API to process VOC datasets, especially for evaluating VOC results using coco's evaluation protocol.
